name: cleanapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  equatable: ^2.0.5
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  get_it: ^8.0.2
  intl: ^0.19.0
  floor: ^1.5.0
  flutter_hooks: ^0.20.5
  dio: ^5.7.0
  retrofit: ^4.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.5
  floor_generator: ^1.5.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
